### ISSUE TITLE
analysis multiple assembled genome bins

### ISSUE THREAD

**Issue by chloelulu** [bio-miga/miga-web#20]
Hi, developer,
Thank you for your time!
I have some assembled genome bins(approximate 100), I want to analysis them in MiGA. Is it available for me to analysis all of them there? Since I see in MiGA website I can only upload them one by one(GZ compression supported (with .gz extension)). Any way to upload all the 100 genome bins? Thanks so much!

**Comment by lmrodriguezr** [comment]
Dear @chloelulu ,
This is one of our projected implementations in the near future. Please see our roadmap:
http://roadmap.microbial-genomes.org

Hopefully we'll be able to provide this feature in website soon. In the meantime, you can use the MiGA infrastructure. We've documented installation instructions using several package managers, including `apt-get`, `homebrew`, and `conda`, and we're happy to provide guidance either here in GitHub or through our support chat: http://support.microbial-genomes.org. If you don't currently have access to the necessary infrastructure, I'm afraid the only option currently is uploading the genomes one by one :-/

Thanks for your interest in MiGA. I'll update this issue once we release the prospected feature.

Best,
Miguel.

**Comment by chloelulu** [comment]
Hi, @lmrodriguezr ,
Appreciate your response. Based on your suggestions, I have used conda to install(https://manual.microbial-genomes.org/part2/requirements/conda). I have used conda install everything except for the following part 
`cd $(gem environment gemdir)
cd ../../$(basename $PWD)/$(gem environment platform | perl -pe 's/.*://')
mv rbconfig.rb rbconfig.rb.bu
perl -pe 's/\/\S*?\/_build_env\/bin\///g' rbconfig.rb.bu > rbconfig.rb`
I think I do not need to install that part. But when I activate miga conda environment. miga function can not be found. Anything wrong with me? 
Looking forward to your suggestion.

**Comment by lmrodriguezr** [comment]
Did you follow the installation steps? https://manual.microbial-genomes.org/part2/installation

If your Ruby is working fine then you don't need that part. Just try:
```bash
gem install miga-base
```

If that works fine, then you'll just have to initialize it (`miga init`).

**Comment by chloelulu** [comment]
Hi, @lmrodriguezr ,
I think I did not do on the page you mentioned. I only included the conda page. I formerly thought conda can install everything, so I just install the conda mentioned page. So I need to go to https://manual.microbial-genomes.org/part2/installation and do all the steps?
Appreciate your help!

**Comment by chloelulu** [comment]
Hi, @lmrodriguezr ,
I am so confused about the installation. I have tried but always failed. 

`gem install miga-base
/home/zzhang78/miniconda2/envs/miga/bin/ruby: error while loading shared libraries: libjemalloc.so.1: cannot open shared object file: No such file or directory`
But I am sure I have successfully installed ruby in conda. 
- And I have added the ~/.miga_modules with 
`#!/bin/bash
# File: ~/.miga_modules

# Enable software installed in this user
export PATH="/home/zzhang78/miniconda2/envs/miga/bin:$PATH"

# Enable MyTaxa
#export PATH="/home/zzhang78/miniconda2/envs/miga/MyTaxa-master:$PATH"`
I marked #export PATH="/home/zzhang78/miniconda2/envs/miga/MyTaxa-master:$PATH", since I did not successfully installed MyTaxa.
May I have the help?
Thank you!!!

**Comment by lmrodriguezr** [comment]
That's because the Ruby that comes in Conda is broken. I detailed how to fix it in the manual, but you can also see more info here: https://github.com/ContinuumIO/anaconda-issues/issues/9863

**Comment by lmrodriguezr** [comment]
Hello @chloelulu 
Sorry for the long delay on reporting, but this has now been implemented in MiGA Web. See also: https://twitter.com/MicroGenomes


Best,
Miguel.
