### ISSUE TITLE
MiGA website down

### ISSUE THREAD

**Issue by kkowalden** [bio-miga/miga-web#35]
Hi @lmrodriguezr

The website appears to be down.
http://microbial-genomes.org/

I am able to log in, but I cannot access any of my files.

Error page returned:

"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

Thanks for your help!
Kim

**Comment by lmrodriguezr** [comment]
Hi @kkowalden 

Thanks for the report! Our back-end server had a network issue, but I have now reestablished the connection. It should be working properly now. Please feel free to reopen if you continue to experience any issues.


Best
Miguel.
