### ISSUE TITLE
MiGA website not available

### ISSUE THREAD

**Issue by kkowalden** [bio-miga/miga-web#38]
Hi @lmrodriguezr

The MiGA website appears to be down again.

Thanks for your assistance.

Kim

**Comment by zdk123** [comment]
still down

**Comment by lmrodriguezr** [comment]
Hello. It seems the webpage was down for a couple of days as per the original report by @kkowalden , but I'm not aware of any recent interruptions.

@zdk123 can you confirm if you're still experiencing any issues? If yes, can you please let us know which URL is causing the problem? Thanks!

Pinging @FangYuan0059 for follow-up.

**Comment by zdk123** [comment]
Having an issue with account activation in part I think because my browser is redirecting to the url to https.

**Comment by zdk123** [comment]
I'm in now. Sorry for the duplicate account but I was impatient waiting for my confirmation email!

**Comment by lmrodriguezr** [comment]
Not a problem at all, I would have done the same :)

**Comment by lmrodriguezr** [comment]
Closing this issue, but please feel free to reopen or open a new one
