### ISSUE TITLE
MiGA website appears to be down

### ISSUE THREAD

**Issue by kkowalden** [bio-miga/miga-web#45]
Hi @lmrodriguezr

The MiGA website appears to be down today.

Thanks,
Kim

**Comment by lmrodriguezr** [comment]
@FangYuan0059 Any insights? Is the system under maintenance?
Thanks!
Miguel.

**Comment by kkowalden** [comment]
Hi @lmrodriguezr

We are still not able to process any data.
Any updates?

Thanks,
Kim

**Comment by FangYuan0059** [comment]
@kkowalden 
Hello Kim,

We are currently immigrating the VM to a new server. It may take one or two more days. I can update you here once the process is completed. Sorry for the inconvenience.

Best,
Fang

**Comment by lmrodriguezr** [comment]
Dear @kkowalden 
Please feel free to use http://uibk.microbial-genomes.org/
This mirror has up-to-date versions of all actively-maintained databases

Best wishes,
Miguel.

**Comment by FangYuan0059** [comment]
@kkowalden 
Hi Kim,
The MiGA website is also up now. Thanks for your patience. Please let us know if you meet any other questions.

Best,
Fang
