### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by galacmr** [bio-miga/miga-web#54]
Hello! The website has been down for several days now. No matter what I try to do it says "We're sorry, but something went wrong.
If you are the application owner check the logs for more information." Is there any information about when it will be back up and running?
Thanks!

**Comment by margaretc-ho** [comment]
@lmrodriguezr I am also having this problem, the website is also down for me. Help?

**Comment by lmrodriguezr** [comment]
Dear both,
It looks like the GeorgiaTech servers are experiencing some issues, but I don't currently have access to rectify the situation. I'll contact the new admins, but in the meantime I'd recommend using the alternative server I have created at University of Innsbruck: https://uibk.microbial-genomes.org/

Unfortunately, the uploaded data and the users are completely independent, so you'll need to setup a user and upload the genomes there, but it should be working properly and it has a newer interface and a more recent version of the TypeMat database.

Best wishes,
Miguel.

**Comment by lmrodriguezr** [comment]
Dear users, our system has now been restored in the Georgia Tech servers as well. Please feel free to use either endopoint.

Best wishes,
Miguel.
