### ISSUE TITLE
MiGA Online not working

### ISSUE THREAD

**Issue by adsweet** [bio-miga/miga-web#65]
Hi,
The MiGA Online platform does not seem to be working. I uploaded contigs using NCBI Prok, and the analysis has been running without progress for over a month. Any suggestions?

Thank you!
Drew Sweet

**Comment by lmrodriguezr** [comment]
Dear @adsweet 
There are several issues with the server in Gatech. My recommendation would be to use instead:
https://lfu.microbial-genomes.org/

Best wishes, Miguel.

**Comment by adsweet** [comment]
Thank you!
